### PR TITLE
Add pyproject toml

### LINKED ISSUE #56: Avoid needing numpy before pip install
```
(py38) denolf@lindenolf:~$ pip install fisx
Collecting fisx
  Using cached fisx-1.2.0.tar.gz (5.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0801lihx/fisx_a061210d946a4e838698022373c18b14/setup.py", line 82, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### PR DESCRIPTION
**Pull request by woutdenolf**
Closes #56

### CODE REVIEW

**Comment by vasole** [comment]
PyMca and fisx seem to build nicely with latest setuptools. Why is setuptools < 60 needed?

**Comment by woutdenolf** [comment]
https://gitlab.esrf.fr/silx/bob/main/-/commit/6b45c44ca55139d09fc2296dec4edaa10932032a

But for pymca it might not matter. I remove the setuptools version bounds.

**Comment by vasole** [comment]
Somehow travis CI is not happy with this PR  (I have just made a couple of PR that have passed)

**Comment by woutdenolf** [comment]
@vasole Seems ok now.

**Review by vasole — APPROVED** [review]

**Comment by vasole** [comment]
The problems with `pyproject.toml` are solved, but something has changed and tests do not pass.

**Pull request merged**
